name: heap-profiler

type: ruby

up:
  - ruby: 2.7.2
  - bundler

commands:
  console:
    desc:   'start a console'
    run:    bin/console
  run:
    desc:   'start the application'
    run:    bin/run
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/testunit
